#' @title Venn diagramm
#' @description To make a Venn diagramm of 2, 3 or 4 lists
#' @param list list of 2 , 3 or 4 character vector
#' @param listnames character list names to display on graph
#' @param returnlist logical
#' @param title character title to display on graph
#' @param plot logical to display the plot or not
#' @param export logical export lists in a directory
#' @param path character
#' @param dirname character name of the directory created when export = T
#' @return venn plot and new lists generated by venn.
#' @examples
#' # library(magrittr)
#' # list(
#' #   c(letters[6:20] , letters[25] ) ,
#' #   letters[1:15] ,
#' #   c( letters[2:5] , letters[8:23] ) ) %>% moal::venn(.)
#' @author Florent Dumont <florent.dumont@universite-paris-saclay.fr>
#' @importFrom magrittr %>%
#' @export
venn <- function(
  list = NULL , listnames = NULL , returnlist = F,
  title = "Venn Diagram", plot = T,
  export = F , path = "." , dirname = "venn" )
{
  if( length( list ) == 2 )
  {
    venn2( list = list , listnames = listnames , returnlist = returnlist , title = title,
           plot = plot , export = export , path = path , dirname = dirname )
  }
  if( length( list ) == 3 )
  {
    venn3( list = list , listnames = listnames , title = title , plot = plot,
           export = export , path = path , dirname = dirname )
  }
  if( length( list ) == 4 )
  {
    venn4( list = list , listnames = listnames , returnlist = returnlist , title = title,
           plot = plot , export = export , path = path , dirname = dirname )
  }
}